# This is a YAML file containing a standard Python logging configuration

version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s'

handlers:
  console:
    class : logging.StreamHandler
    formatter: precise
    level   : INFO
    stream  : ext://sys.stdout

  file:
    class : logging.handlers.TimedRotatingFileHandler
    formatter: precise
    level: DEBUG
    filename: debug.log

  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: precise
    filename: error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  app:
    level: DEBUG
    handlers: [console, file, error]

root:
  level: DEBUG
  handlers: [console]

disable_existing_loggers: false
